### ISSUE TITLE
Order Checkout Functionality Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#10]
The application currently lacks a fully implemented checkout process for users to finalize their orders. This feature is crucial for ensuring that users can purchase items, provide necessary information (like payment and shipping details), and complete their orders successfully.

**Steps to Reproduce**
1. Add items to the shopping cart.
2. Click on the checkout button.
3. Observe that nothing happened.

**Expected Behavior**
- The checkout Process should include the following steps:
1. Cart Review: Allow users to review the items in their cart, including quantity, price, and item description.
2. Pick-Up Options: Users should be able to select pick-up options, including scheduling a pick-up time.
3. Payment Information: Allow users to choose payment method and proceed with it.
4. Order Confirmation: Display a final summary of the order after ordering, including total cost.

**Actual Behavior**
- Users are unable to proceed to checkout.
- There is no way for users to finalize or confirm the order.

Environment: 
- Windows 11.

![image](https://github.com/user-attachments/assets/db6b49dd-7fb5-4997-8e26-085bbd8409dc)

**Comment by Jouriab** [comment]
As a student or faculty member, I want to choose my preferred payment method (credit card or cash) so that I can pay in the most convenient way for me.

**Comment by Jouriab** [comment]
As a student or faculty member, I want a checkout button on the cart page so that I can proceed to the payment page when I'm ready.

**Comment by Jouriab** [comment]
As a university administrator, I want to ensure compliance with university payment policies on the platform so that all transactions are processed securely and in accordance with financial regulations.

**Comment by RahafDaas** [comment]
This issue has been resolved by adding functionalities to the checkout buttons and event handlers like onclick and on submit. Also different payment methods have been created like pay on pick up, online, and points. In addition, a confirmation page has been created to be displayed after the successful order creation process which displayed all required details of an order. 

**Steps to ensure successful resolution of issue:**
1. Log in. 
2. Add an item to cart.
3. Choose pick up time.
4. Choose payment method.
5. press on checkout to proceed to order confirmation page. 

**Screenshots of successful order process:**
![Screenshot (953)](https://github.com/user-attachments/assets/1136a129-0358-4f33-9500-1a93822dd723)
![Screenshot (954)](https://github.com/user-attachments/assets/7da7b00a-61c4-4c15-a77c-b1759d0b4612)
![Screenshot (955)](https://github.com/user-attachments/assets/955ff599-fd08-4666-a41c-76fb4b11a08d)
