### ISSUE TITLE
Order Reviewing Functionality Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#12]
The application currently lacks a feature for users to review their orders after completion. This feature is important for users to ensure their order details are correct, confirm items, and prices.

**Steps to Reproduce**
1. Add items to the cart and proceed to checkout.
2. Observe that there is no order review page to confirm the details of the order.

**Expected Behavior**
- After the final confirmation, users should be presented with an order review page that shows:
- A list of the items being purchased (name, description, quantity, price).
- Payment information.
- Final total cost.

**Actual Behavior**
- There is no page or functionality to review the order after submission.

Environment:
- Windows 11.

![Screenshot (952)](https://github.com/user-attachments/assets/d9ab7ff6-c028-4e66-a04e-9d131a244e96)

**Comment by Jouriab** [comment]
As a student or faculty member, I want to review my order before confirming it so that I can make any necessary changes before checkout.

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to communicate directly with customers through the platform in case of order modifications or delays so that I can provide excellent customer service.

**Comment by RahafDaas** [comment]
This issue has been resolved by creating an order confirmation page and adding a confirmation alert message stating a question to confirm whether that user is ready to proceed to confirm the order. 

Steps to ensure successful resolution of issue:
1. Log in.
2. Add items to cart.
3. Add all required data.
4. Press on checkout button.
5. Order Confirmation page is displayed.

**Screenshots of successful resolution of issue:** 
![Screenshot (955)](https://github.com/user-attachments/assets/539f8237-7dda-4acf-a044-2f902013b191)
![Screenshot (954)](https://github.com/user-attachments/assets/4a4a6fc8-f743-477c-a75b-e597fe1c21b8)
![Screenshot (953)](https://github.com/user-attachments/assets/9ba2a8e7-21b4-485a-9933-e30f18009dbf)
