### ISSUE TITLE
Order confirmation

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#13]
The application currently lacks a feature for users to review their orders after completion. This feature is important for users to ensure their order details are correct, confirm items, and prices.

**Steps to Reproduce**
1. Add items to the cart and proceed to checkout.
2. Observe that there is no order review page to confirm the details of the order.

**Expected Behavior**
- After the final confirmation, users should be presented with an order review page that shows:
- A list of the items being purchased (name, description, quantity, price).
- Payment information.
- Final total cost.

**Actual Behavior**
- There is no page or functionality to review the order after submission.
- 
**Environment:**
- Windows 11.

![Screenshot (952)](https://github.com/user-attachments/assets/29ea1999-816c-477b-b086-9a607b5a0e8a)

**Comment by Jouriab** [comment]
As a student or faculty member, I want to receive a confirmation message for my order and check the remaining time until it is ready for pickup so that I can manage my time effectively.

**Comment by Jouriab** [comment]
As a student or faculty member, I want to receive a confirmation message for my order and check the remaining time until it is ready for pickup so that I can manage my time effectively

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to mark an order as "ready for pickup" in the system so that customers are notified when their food is available.

**Comment by RahafDaas** [comment]
This issue has been resolved by creating an order confirmation page and adding a confirmation alert message stating a question to confirm whether that user is ready to proceed to confirm the order.

**Steps to ensure successful resolution of issue:**
1. Log in.
2. Add items to cart.
3. Add all required data.
4. Press on checkout button.
5. Order Confirmation page is displayed.


**Screenshots of successful resolution of issue:**
![Screenshot (953)](https://github.com/user-attachments/assets/39c08b5c-0a98-4dcb-bf44-e73d635e8b4e)
![Screenshot (954)](https://github.com/user-attachments/assets/8e3d5995-f83d-419c-869d-a81b12068c45)
![Screenshot (955)](https://github.com/user-attachments/assets/7edaa976-52f3-4862-ad2d-4f14119f8e65)
