### ISSUE TITLE
Order Picked Up Status Functionality Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#14]
The application currently lacks a status update feature to mark orders as "picked up." This functionality is essential for informing both the shop owners and users when the order is successfully picked up.

Steps to reproduce:
1. Login.
2. create and order and proceed to order confirmation.
3. update the status of the order.
4. notice that the order status is not updated. 

**Expected Behavior**
User places an order, order goes to shop owner, shop owner confirms order, then changes status of order to picked up after picking up. 

**Actual Behaviour**
Data in user order history is not updated after the shop owner has changed the order status. 

Environment:
- Windows 11.
![Uploading image.png…]()

**Comment by Jouriab** [comment]
As a student or faculty member, I want to choose between picking up my order or having it delivered so that I can select the most convenient option.

**Comment by Jouriab** [comment]
As a student or faculty member, I want to receive a success message when my order is delivered so that I know it has been successfully completed.

**Comment by RahafDaas** [comment]
This issue has been resolved by modifying the process updating the user's order data in shop owner page using the MongoDB queries. 

Steps to ensure successful resolution of issue:
1. Login.
2. Add items to cart.
3. Checkout.
4. Notice the order status when update status button is clicked and shop owner changes the status, data is updated then. 

Screenshots to successful resolution of issue:
![Screenshot (957)](https://github.com/user-attachments/assets/a87b81c9-55ae-4d25-8fd2-a5b368dc3d6d)
![Screenshot (959)](https://github.com/user-attachments/assets/31c0675b-aeea-44d4-bbf3-ad50d6c2aadc)
![Screenshot (958)](https://github.com/user-attachments/assets/4fa815f7-b575-480c-8035-abb8cf398b76)
