### ISSUE TITLE
Order History Page Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#15]
The application currently lacks a page where users can view their past orders. An order history page is essential for customers to track their order history, and view order details. This feature will enhance user experience by allowing users to easily access information about their previous purchases.

**Steps to Reproduce**
1. Log in.
2. Navigate to homepage.
3. Notice that no order history or past order details are available.

**Expected Behavior**
In home page an Order History  button is present to redirect users to the order history page where all orders associated with the user are displayed. 

**Actual Behaviour**
The My orders button does not work.

Environemnt:
- Windows 11.

![Screenshot (939)](https://github.com/user-attachments/assets/7e60219b-b485-4374-b502-a339d6f75b43)

**Comment by Jouriab** [comment]
As a student or faculty member, I want to see a brief description of the restaurant's or coffee shop's location so that I know where to pick up my order.

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to view customer feedback and ratings so that I can understand their satisfaction level and identify areas for improvement.

**Comment by RahafDaas** [comment]
This issue has been resolved by creating an order history page that displayed the user orders successfully created. despite the order status, all orders of this user are displayed. 

Steps to ensure successful resolution of issue:
1. Log In.
2. View the Home page.
3. Search for Order History Button.
4. Click it.
5. Order History page is displayed. 

Screenshot of successful resolution of issue:
![image](https://github.com/user-attachments/assets/e13c9421-11bb-40b7-ba31-6cccdea6e499)
