### ISSUE TITLE
Order Review Functionality Missing

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#17]
The application currently lacks an order review feature that allows users to add a review feedback after ordering. This feature helps in enhancing user experience and process of ordering. 

**Steps to Reproduce:**
1. Add items to cart.
2. Checkout.
3. View order confirmation.
4. Click on review order button.
5. It does not work.

Expected Behaviour:
After creating an order users must be able to write a review of their order.

Actual Behaviour:
The review page is not available after clicking on review order. 

Environment:
- Windows 11.

![Screenshot (967)](https://github.com/user-attachments/assets/907dba14-c759-451a-8ca7-601c02266720)

**Comment by Jouriab** [comment]
As a student or faculty member, I want to rate the restaurant or coffee shop (0-5 stars) after my order so that I can share my feedback with others.

**Comment by Jouriab** [comment]
As a restaurant/coffee shop owner, I want to view customer feedback and ratings so that I can understand their satisfaction level and identify areas for improvement.

**Comment by RahafDaas** [comment]
This issue has been resolved by creating an order review page and a collection to store the reviews. Users can now enter a feedback and rating of the order. 

**Steps to ensure successful resolution of the issue:**
1. Log in.
2. Add items to the cart.
3. Checkout.
4. Click on the review button.
5. Add review.
6. An alert is displayed.
7. Review created successfully. 

**Screenshots:**
![Screenshot (966)](https://github.com/user-attachments/assets/9c8fc836-7314-4f84-9b11-899b8a13ca4d)
![Screenshot (967)](https://github.com/user-attachments/assets/34facebd-f29d-402f-a369-59bb964b4266)
![Screenshot (968)](https://github.com/user-attachments/assets/b79af0fa-2aff-4d6f-9966-ba91f92cdf71)
![Screenshot (969)](https://github.com/user-attachments/assets/62f237c6-c164-4552-bb3c-530a6d08f107)
