### ISSUE TITLE
Inconsistent Styling For Add New Store Page

### ISSUE THREAD

**Issue by leenalroomi** [RahafDaas/SE499-Senior-Project#25]
The "Add New Store" page exhibits inconsistent styling across different sections, which leads to a poor user experience. This includes mismatched font sizes, inconsistent button styles, misaligned form fields, and irregular spacing between elements. These inconsistencies make the page look unpolished and can confuse users when interacting with the page.

**Steps to Reproduce**
1. Navigate to the "Add New Store" page from the dashboard or the relevant menu.
2. Observe the styling of various elements such as form fields, buttons, and headings.
3. Notice any differences in font styles, button shapes, alignment, or spacing.
4. Compare the page’s design with other pages of the site to spot discrepancies.

**Expected Behaviour:**
All font styles must be consistent and no more than two styles to be used per page. 

**Actual Behaviour:**
More than two font styles are used. 
Environment: 
- Windows 11.

**Screenshot:** 
![image](https://github.com/user-attachments/assets/5c417882-8e4b-4ab3-be77-9a83adb011ca)

**Comment by RahafDaas** [comment]
This issue has been resolved successfully by restricting the use of font styles to maximum of two styles per page to help in making the website more consistent and efficient. 

**Steps for successful issue resolution:**
1. Navigate to add menu item page.
2. Notice that no more than two font styles are used. 

**Screenshots:**
![image](https://github.com/user-attachments/assets/697edf1b-aadd-499c-ac6d-0f91628b31a6)
