### ISSUE TITLE
PSUEats Homepage

### ISSUE THREAD

**Issue by eng-Raneem-Haitham** [RahafDaas/SE499-Senior-Project#26]
The buttons on the shop owner dashboard have inconsistent styles, leading to a disjointed user experience. Some buttons have different sizes, colors, hover effects, and text alignments, which makes the page appear unpolished. For a cohesive design, buttons should follow a consistent style guide that aligns with the overall design system of the website.

**Steps to Reproduce**
1. Navigate to the shop owner dashboard.
2. Observe the buttons present on the page (e.g., "Profile", "Log Out").
3. Notice inconsistencies such as:
      - Different button sizes (height and width).
      - Different colors for primary and secondary actions.
      - Inconsistent hover effects.
      - Misaligned text inside the buttons.

**Expected Behavior**
- Consistent Button Sizes: All buttons should have a uniform height, padding, and width.
- Consistent Colors: Buttons should have consistent colors based on their function.
- Consistent Hover Effects: All buttons should have the same hover effect, such as a color change or a shadow, to provide uniform interaction feedback.
- Aligned Text: Button text should be centered and follow a consistent font size and style.

**Actual Behavior**
- Different Sizes: Some buttons are larger or smaller than others, which creates a visually inconsistent layout.
- Different Colors: Primary buttons (like "Save" or "Submit") are sometimes a different color than secondary buttons (like "Cancel" or "Edit").
- Inconsistent Hover Effects: Some buttons have hover effects (such as color change or background shading), while others do not.
- Text Misalignment: Some button texts are slightly misaligned, causing buttons to look uneven.

Environment:
- Windows 11.

**Screenshots:**
![Screenshot (972)](https://github.com/user-attachments/assets/8eb94deb-4557-424d-a1d8-841d9c9c87cd)

**Comment by RahafDaas** [comment]
This issue has been resolved by updating and modifying the styles of buttons to be more consistent and user-friendly. These changes were mainly done using CSS.

**Steps to ensure successful issue resolution:**
1. Navigate to the shop owner dashboard.
2. Notice consistent styles and colors.

**Screenshot:**
![Screenshot (974)](https://github.com/user-attachments/assets/d1e8b503-83a1-4636-9a14-f14dca65b66f)
