### ISSUE TITLE
Order History Button Disabled

### ISSUE THREAD

**Issue by eng-Raneem-Haitham** [RahafDaas/SE499-Senior-Project#27]
The application currently lacks a page where users can view their past orders. An order history page is essential for customers to track their order history, and view order details. This feature will enhance user experience by allowing users to easily access information about their previous purchases.

**Steps to Reproduce**
1. Log in.
2. Navigate to homepage.
3. Notice that no order history or past order details are available.

**Expected Behavior**
In the home page, an Order History button is present to redirect users to the order history page where all orders associated with the user are displayed.

**Actual Behaviour**
The My Orders button does not work.

**Environment:**
Windows 11.

Screenshots: 
![Screenshot (930)](https://github.com/user-attachments/assets/fba86f48-be6c-4f3d-a066-1005fbe63abd)

**Comment by RahafDaas** [comment]
This issue has been resolved by creating an order history page that displayed the user orders successfully created. despite the order status, all orders of this user are displayed.

**Steps to ensure successful resolution of issue:**
1. Log In.
2. View the Home page.
3. Search for Order History Button.
4. Click it.
5. Order History page is displayed.

**Screenshot of successful resolution of issue:**
![Screenshot (931)](https://github.com/user-attachments/assets/80c79790-1980-4b88-9bce-711bc2365360)
![Screenshot (962)](https://github.com/user-attachments/assets/99560c94-ca06-4e38-bebb-4a2581853a30)
