### ISSUE TITLE
Pop up message

### ISSUE THREAD

**Issue by eng-Raneem-Haitham** [RahafDaas/SE499-Senior-Project#28]
The website is missing a Proceeding to Checkout pop-up message that should appear when the user clicks on the checkout button. This message serves as a confirmation to users that they are about to leave the shopping page and proceed to the checkout process. Without this confirmation, users may unintentionally proceed to checkout without realizing the next steps or if they need to review their cart items. Adding this pop-up can enhance the user experience by ensuring they are making an informed action.

**Steps to Reproduce**
1. Add items to the shopping cart.
2. Navigate to the cart or checkout page.
3. Click the "Checkout" button.
4. Notice that no confirmation or pop-up message appears before the user is redirected to the checkout page.

**Expected Behavior**
- A pop-up message should appear when the user clicks the "Proceed to Checkout" button.
- The pop-up should display a clear message such as:
- "Are you sure you want to proceed to checkout?"
- with the options to either:
        - Proceed: Continue to the checkout page.
        - Cancel: Return to the cart or stay on the current page.

**Actual Behavior**
- Clicking the "Proceed to Checkout" button redirects the user immediately to the checkout page without any confirmation.
- There is no pop-up or modal to confirm the user's intention.

**Environment:**
- Windows 11.

**Screenshot:**
![Screenshot (950)](https://github.com/user-attachments/assets/b001bfed-2fc2-40a2-abd5-f4ffa248273e)

**Comment by RahafDaas** [comment]
This issue has been resolved by adding a modal pop-up message when the checkout button is clicked. The pop-up message states a question to ask whether user is ready to checkout the order and pay or not. 

**Steps to ensure successful resolution of the issue:**
1. Add items to the cart.
2. Fill required details.
3. Click checkout button.
4. A modal pop-up message is displayed.

**Screenshot:**
![Screenshot (953)](https://github.com/user-attachments/assets/a268801b-c374-425c-9233-75f2f72396be)
![Screenshot (954)](https://github.com/user-attachments/assets/0adffe9a-59cb-4ee2-bd9f-3b1a88197e14)
