### ISSUE TITLE
Checkout Button Did not Work

### ISSUE THREAD

**Issue by eng-Raneem-Haitham** [RahafDaas/SE499-Senior-Project#29]
The checkout button is not working in the cart page. when the button is pressed nothing happens and no order confirmation is displayed. This button is essential to the success of the website since after it the order is placed. 

Steps to Reproduce:
1. add items to cart.
2. press checkout button.
3. Nothing happens.

Expected Behaviour:
An order confirmation page is displayed after the checkout and pop-up message are pressed. 

Actual Behaviour:
Nothing was displayed after the checkout button is diplayed. 

Environment: 
- Windows 11.
![Screenshot (950)](https://github.com/user-attachments/assets/29100c6f-3d72-4bb8-994a-68dff4fe6f25)

**Comment by RahafDaas** [comment]
This issue has been resolved by updating the mapping settings between the cart page and the order confirmation page. To have the workflow of an order to work. 

**Steps to ensure successful resolution of the issue:**
1. Add items to cart 
2. Press checkout button.
3. A Pop-up message is displayed. 
4. Order confirmation page is displayed. 

**Screenshot:**
![Screenshot (953)](https://github.com/user-attachments/assets/2b5035e6-f3f2-41cb-bb39-06e957e7da06)
![Screenshot (954)](https://github.com/user-attachments/assets/d9e1a53d-73d7-4cd2-97be-9dbcec61b082)
![Screenshot (955)](https://github.com/user-attachments/assets/e720553a-9fbf-47c4-92ff-73bb01a669b8)
