### ISSUE TITLE
Home Button on Homepage is Disabled

### ISSUE THREAD

**Issue by eng-Raneem-Haitham** [RahafDaas/SE499-Senior-Project#30]
The "Home" button on the Menu Page is currently disabled, making it unclickable. This creates confusion for users who expect to be able to navigate back to the homepage from this page. A functional "Home" button is essential for user navigation and accessibility. This issue needs to be addressed to ensure that the button works properly.

**Steps to Reproduce**
1. Navigate to the Menu Page of Selu Cafe.
2. Locate the "Home" button.
3. Attempt to click the "Home" button.
4. Notice that the button is disabled or unresponsive, preventing the user from being able to navigate back to the homepage.

**Expected Behavior**
- The "Home" button should be clickable and should navigate the user back to the homepage when clicked.
- The button should be enabled and visually appear interactive, not grayed out or disabled.

**Actual Behavior**
- The "Home" button is disabled.
- Clicking the button has no effect, and the user cannot return to the homepage from certain pages.
 Environment:
-  Windows 11.

Screenshot:
![Uploading image.png…]()

**Comment by RahafDaas** [comment]
This issues has been resolved by simply changing the mapping of the button "Home" in all pages. As a result, now users can navigate to homepage by clicking on the home button where it is displayed. 

Steps to ensure successful resolution of issue:
1. Navigate to Selu Cafe.
2. Click on Home button in the nav section.
3. Home page is displayed.

 Screenshots:
![Screenshot (975)](https://github.com/user-attachments/assets/54a87faa-f8e3-465e-9b9f-547eb80a10ec)
![Screenshot (976)](https://github.com/user-attachments/assets/807a6630-27ab-4d08-9455-046fc7d8530f)
