### ISSUE TITLE
Shop Name Missing Field in Shop Owner Registration Page

### ISSUE THREAD

**Issue by SomouMS** [RahafDaas/SE499-Senior-Project#35]
**Issue Description:** 
When shop owner Registers a new account, the system requests him/her to enter specific fields such as name, phone number, password, etc. However, there is no field for the shop name itself which colides with the shop owner's name. A s a result this confuses the shop owners when they want to register.  

**Steps of Reproduce:**
1. Open the website,
2. Notice the Registering process of Shop owner does not contain Shop Name. 

**Expected Behaviour:**
- Any shop owner when he/she wants to register, both shop owner name and shop name are e=requested. 

**Actual Behaviour:**
- No shop Name field is displayed or requested. 

Environment:
- Windows 11. 

**Screenshot:**
![image](https://github.com/user-attachments/assets/ce123a29-5dcd-4774-b020-4dec564a8740)

**Comment by RahafDaas** [comment]
This issue has been resolved by modifying the form section in the Shop Owner registration page via adding a shop name input. Also, the shop owner schema is also updated to accept this field. 

**Steps for successful resolution of issue:**
1.Open the website.
Notice the Shop Name field is added. 

**Screenshot:**
![image](https://github.com/user-attachments/assets/0ad5e538-689a-41cb-be74-deede7e23285)
