### ISSUE TITLE
Incorrect Image Uploading Process in Shop Owner Registration

### ISSUE THREAD

**Issue by SomouMS** [RahafDaas/SE499-Senior-Project#36]
**Issue Description:** 
While trying to Sign Up as a new shop owner, an Iqama/national ID field is required. However, and while the field should accept the input as an image, the current system is accepting the input as string. 

**Steps to Reproduce:**
1. Navigate to Shop Onwer Regsitration Page.
2. Notice the text input of ID number it must be a file input.

**Expected Behaviour:**
- Any shop owner must upload their ID image to the website.

**Actual Behavior:**
- A text input field is available only. 

**Environment:**
- Windows 11. 

**Screenshot:**
![image](https://github.com/user-attachments/assets/6fb8928d-9a81-4127-871b-cf496f7c298c)

**Comment by RahafDaas** [comment]
This issue has been resolved by replacing the text input field into a file input field to allow shop owners to upload their ID images and for admin to verify the shop owner. 

**Steps:**
1. Navigate to the shop owner registration page.
2. Notice the file input is present. 

**Screenshot:**
![Screenshot (978)](https://github.com/user-attachments/assets/c24c75f7-df00-42e1-96c2-44cbae6768bb)
