### ISSUE TITLE
Unfamiliar Routes Are Not Handled Correctly.

### ISSUE THREAD

**Issue by RahafSary** [RahafDaas/SE499-Senior-Project#37]
The application fails to handle unfamiliar or undefined routes gracefully. When a user navigates to a non-existent URL or an undefined route, they encounter a generic error message, a blank page, or no feedback at all. This behavior can confuse users and negatively impact their experience. A proper 404 error page or a fallback mechanism should be implemented to handle such cases.

**Steps to Reproduce**
1. Open the application in a web browser.
2. Manually modify the URL to navigate to a non-existent route (e.g., /undefined-route).
3. Observe how the application responds to the unfamiliar route.

**Expected Behavior**
- When users navigate to an unfamiliar route, they should be directed to a custom 404 Error Page with a user-friendly message.

**Actual Behavior**
- Users encounter A raw server error or stack trace, which is not user-friendly.

![Screenshot (825)](https://github.com/user-attachments/assets/d3b35b9b-7ae8-4e55-8ae4-5038c8d5451e)

**Comment by RahafDaas** [comment]
This issue has been resolved successfully by adding an error route to handle unfamiliar routes and creating an error page. 

 **Steps to ensure successful resolution of the issue:**
1. Search for any route like HTTP://localhost:3000/pass
2. The created error page is displayed successfully. 

**Screenshot:**
![image](https://github.com/user-attachments/assets/d211ae1a-505d-46e0-b708-12f424cf1490)
