### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Jouriab** [RahafDaas/SE499-Senior-Project#5]

**Comment by Jouriab** [comment]
As a student or faculty member, I want to search for a specific restaurant or coffee shop using a search bar so that I can quickly find my preferred place to order from.

**Comment by RahafDaas** [comment]
As mentioned in the issue, the search bar was missing which is an important feature. the issue has been resolved by creating a search bar div and input, and configuring the front end script to handle the search function. 
**Steps to ensure search bar is running:** 
- Log in.
- Allocate the search bar on the user home page.
- Type any restaurant title to search for.
- Restaurant is displayed. 

![Screenshot (931)](https://github.com/user-attachments/assets/7a9dd79d-8688-4b6c-bda9-e20914ca58a2)
